[build]
  base = "client"
  command = "npm cache clean --force && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://hosting-s1hz.onrender.com"
  NODE_ENV = "production"
